import image from './chalinLow.jpg'
import './App.css';
import ImageEffect from 'react-image-effects'

function App() {
    return (
        <div className="App">
            <header className="App-header">
                <div className="images">
                    <ImageEffect
                        url={image}
                        effect="airbrush"
                        width="463px"
                        height="463px"
                    />
                    <ImageEffect
                        url={image}
                        effect="chalkboard"
                        width="463px"
                        height="463px"
                    >
                    </ImageEffect>
                    <ImageEffect
                        url={image}
                        effect="collage"
                        width="463px"
                        height="463px"
                    >
                    </ImageEffect>
                    <ImageEffect
                        url={image}
                        effect="colored-chalkboard"
                        width="463px"
                        height="463px"
                    >
                    </ImageEffect>
                    <ImageEffect
                        url={image}
                        effect="colored-pencil"
                        width="463px"
                        height="463px"
                    >
                    </ImageEffect><ImageEffect
                    url={image}
                    effect="emboss"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="flannel"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="hallucination"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="infrared"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="low-ink-h"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="low-ink-v"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="mirror-h"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="mirror-v"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="mosaic"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="night-vision"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="pencil"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="photo-border"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="selective-color"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="warhol"
                    width="463px"
                    height="463px"
                >
                </ImageEffect><ImageEffect
                    url={image}
                    effect="watercolor"
                    width="463px"
                    height="463px"
                >
                </ImageEffect>
                </div>
            </header>
        </div>
    );
}

export default App;
